# Generated by Django 5.1.4 on 2025-01-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_savedurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_url',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
